apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{repl ConfigOption "namespace"}}
  name: example-nginx
  labels:
    app: example
    component: nginx
spec:
  replicas: {{repl ConfigOption "nginx_replicas" }}
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      labels:
        app: example
        component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          envFrom:
          - configMapRef:
              name: example-config
          resources:
            limits:
              memory: '{{repl ConfigOption "nginx_memory"}}'
              cpu: '500m'





